MASTER_LIBRARY = [
    # --- COMPOUND PUSH ---
    {"name": "Machine Chest Press", "impact": {"Pectorals": 1.0}, "secondary": {"Front Delts": 0.5, "Triceps": 0.5}, "equip": "Selectorized", "gentle": True},
    {"name": "Hammer Strength Flat", "impact": {"Pectorals": 1.0}, "secondary": {"Front Delts": 0.5, "Triceps": 0.5}, "equip": "Plate-Loaded", "gentle": True},
    {"name": "Incline Machine Press", "impact": {"Pectorals": 1.0}, "secondary": {"Front Delts": 0.5, "Triceps": 0.5}, "equip": "Selectorized", "gentle": True},
    {"name": "Dumbbell Flat Press", "impact": {"Pectorals": 1.0}, "secondary": {"Front Delts": 0.5, "Triceps": 0.5}, "equip": "Dumbbells", "gentle": False},
    {"name": "Dumbbell Incline Press", "impact": {"Pectorals": 1.0}, "secondary": {"Front Delts": 0.5, "Triceps": 0.5}, "equip": "Dumbbells", "gentle": False},
    {"name": "Floor Press (DB)", "impact": {"Pectorals": 1.0}, "secondary": {"Triceps": 0.5}, "equip": "Dumbbells", "gentle": True},
    {"name": "Shoulder Press (Machine)", "impact": {"Front Delts": 1.0}, "secondary": {"Side Delts": 0.5, "Triceps": 0.5}, "equip": "Selectorized", "gentle": True},
    {"name": "Dumbbell Shoulder Press", "impact": {"Front Delts": 1.0}, "secondary": {"Side Delts": 0.5, "Triceps": 0.5}, "equip": "Dumbbells", "gentle": False},
    {"name": "Barbell Overhead Press", "impact": {"Front Delts": 1.0}, "secondary": {"Side Delts": 0.5, "Triceps": 0.5}, "equip": "Barbell", "gentle": False},
    {"name": "Arnold Press", "impact": {"Front Delts": 1.0}, "secondary": {"Side Delts": 0.5, "Triceps": 0.5}, "equip": "Dumbbells", "gentle": False},
    {"name": "Smith Machine OHP", "impact": {"Front Delts": 1.0}, "secondary": {"Side Delts": 0.5, "Triceps": 0.5}, "equip": "Smith Machine", "gentle": True},
    {"name": "Low-to-High Cable Fly", "impact": {"Pectorals": 1.0}, "secondary": {"Front Delts": 0.5}, "equip": "Cables", "gentle": True},
    {"name": "High-to-Low Cable Fly", "impact": {"Pectorals": 1.0}, "secondary": {"Front Delts": 0.5}, "equip": "Cables", "gentle": True},
    {"name": "Landmine Press", "impact": {"Pectorals": 1.0}, "secondary": {"Front Delts": 0.5, "Triceps": 0.5}, "equip": "Barbell", "gentle": True},
    {"name": "Close Grip Bench Press", "impact": {"Triceps": 1.0}, "secondary": {"Pectorals": 0.5, "Front Delts": 0.5}, "equip": "Barbell", "gentle": False},
    {"name": "JM Press", "impact": {"Triceps": 1.0}, "secondary": {"Front Delts": 0.5}, "equip": "Barbell", "gentle": False},
    {"name": "Weighted Dips", "impact": {"Pectorals": 1.0}, "secondary": {"Triceps": 0.5, "Front Delts": 0.5}, "equip": "Dumbbells", "gentle": False},
    {"name": "Weighted Push-Ups", "impact": {"Pectorals": 1.0}, "secondary": {"Front Delts": 0.5, "Triceps": 0.5}, "equip": "Dumbbells", "gentle": False},
    {"name": "Single Arm DB Shoulder Press", "impact": {"Front Delts": 1.0}, "secondary": {"Side Delts": 0.5, "Triceps": 0.5}, "equip": "Dumbbells", "gentle": False},
    {"name": "Z-Press", "impact": {"Front Delts": 1.0}, "secondary": {"Side Delts": 0.5, "Upper Back": 0.5}, "equip": "Barbell", "gentle": False},
    {"name": "Upright Row (Cable)", "impact": {"Side Delts": 1.0}, "secondary": {"Rear Delts": 0.5, "Upper Back": 0.5}, "equip": "Cables", "gentle": True},
    {"name": "Behind the Neck Press", "impact": {"Side Delts": 1.0}, "secondary": {"Front Delts": 0.5, "Triceps": 0.5}, "equip": "Barbell", "gentle": False},
    {"name": "Tate Press", "impact": {"Triceps": 1.0}, "secondary": {}, "equip": "Dumbbells", "gentle": True},

    # --- COMPOUND PULL ---
    {"name": "Lat Pulldown (Wide)", "impact": {"Upper Back": 1.0}, "secondary": {"Rear Delts": 0.5, "Biceps": 0.5}, "equip": "Cables", "gentle": True},
    {"name": "Seated Cable Row", "impact": {"Upper Back": 1.0}, "secondary": {"Rear Delts": 0.5, "Biceps": 0.5}, "equip": "Cables", "gentle": True},
    {"name": "Chest-Supported Row", "impact": {"Upper Back": 1.0}, "secondary": {"Rear Delts": 0.5, "Biceps": 0.5}, "equip": "Plate-Loaded", "gentle": True},
    {"name": "One-Arm DB Row", "impact": {"Upper Back": 1.0}, "secondary": {"Rear Delts": 0.5, "Biceps": 0.5}, "equip": "Dumbbells", "gentle": False},
    {"name": "Assisted Pull-Up", "impact": {"Upper Back": 1.0}, "secondary": {"Rear Delts": 0.5, "Biceps": 0.5}, "equip": "Selectorized", "gentle": True},
    {"name": "T-Bar Row (Supported)", "impact": {"Upper Back": 1.0}, "secondary": {"Rear Delts": 0.5, "Biceps": 0.5}, "equip": "Plate-Loaded", "gentle": True},
    {"name": "Barbell Row", "impact": {"Upper Back": 1.0}, "secondary": {"Rear Delts": 0.5, "Biceps": 0.5}, "equip": "Barbell", "gentle": False},
    {"name": "Seal Row", "impact": {"Upper Back": 1.0}, "secondary": {"Rear Delts": 0.5, "Biceps": 0.5}, "equip": "Dumbbells", "gentle": True},
    {"name": "Single Arm High Row", "impact": {"Upper Back": 1.0}, "secondary": {"Rear Delts": 0.5, "Biceps": 0.5}, "equip": "Cables", "gentle": True},
    {"name": "Deadlift (Sumo or Conventional)", "impact": {"Hamstrings/Glutes": 1.0, "Upper Back": 1.0}, "secondary": {"Quads": 0.5, "Rear Delts": 0.5}, "equip": "Barbell", "gentle": False},
    {"name": "Meadows Row", "impact": {"Upper Back": 1.0}, "secondary": {"Rear Delts": 0.5}, "equip": "Barbell", "gentle": False},
    {"name": "Neutral Grip Lat Pulldown", "impact": {"Upper Back": 1.0}, "secondary": {"Biceps": 0.5}, "equip": "Cables", "gentle": True},
    {"name": "Straight Arm Cable Pulldown", "impact": {"Upper Back": 1.0}, "secondary": {"Triceps": 0.5}, "equip": "Cables", "gentle": True},
    {"name": "Incline DB Row", "impact": {"Upper Back": 1.0}, "secondary": {"Rear Delts": 0.5}, "equip": "Dumbbells", "gentle": True},
    {"name": "Single Arm Lat Pulldown", "impact": {"Upper Back": 1.0}, "secondary": {"Biceps": 0.5}, "equip": "Cables", "gentle": True},
    {"name": "Pendlay Row", "impact": {"Upper Back": 1.0}, "secondary": {"Hamstrings/Glutes": 0.5, "Biceps": 0.5}, "equip": "Barbell", "gentle": False},
    {"name": "Rack Pulls", "impact": {"Upper Back": 1.0, "Hamstrings/Glutes": 1.0}, "secondary": {"Forearms": 0.5}, "equip": "Barbell", "gentle": False},

    # --- LEGS ---
    {"name": "Leg Press (45 Deg)", "impact": {"Quads": 1.0}, "secondary": {"Hamstrings/Glutes": 0.5, "Calves": 0.5}, "equip": "Sled Machine", "gentle": True},
    {"name": "Hack Squat", "impact": {"Quads": 1.0}, "secondary": {"Hamstrings/Glutes": 0.5}, "equip": "Sled Machine", "gentle": True},
    {"name": "V-Squat Machine", "impact": {"Quads": 1.0}, "secondary": {"Hamstrings/Glutes": 0.5}, "equip": "Sled Machine", "gentle": True},
    {"name": "Goblet Squat", "impact": {"Quads": 1.0}, "secondary": {"Hamstrings/Glutes": 0.5}, "equip": "Dumbbells", "gentle": False},
    {"name": "Bulgarian Split Squat", "impact": {"Quads": 1.0}, "secondary": {"Hamstrings/Glutes": 0.5}, "equip": "Dumbbells", "gentle": False},
    {"name": "Smith Machine Squat", "impact": {"Quads": 1.0}, "secondary": {"Hamstrings/Glutes": 0.5}, "equip": "Smith Machine", "gentle": True},
    {"name": "Pendulum Squat", "impact": {"Quads": 1.0}, "secondary": {"Hamstrings/Glutes": 0.5}, "equip": "Plate-Loaded", "gentle": True},
    {"name": "Seated Leg Curl", "impact": {"Hamstrings/Glutes": 1.0}, "secondary": {}, "equip": "Selectorized", "gentle": True},
    {"name": "Lying Leg Curl", "impact": {"Hamstrings/Glutes": 1.0}, "secondary": {}, "equip": "Selectorized", "gentle": True},
    {"name": "Romanian Deadlift", "impact": {"Hamstrings/Glutes": 1.0}, "secondary": {"Upper Back": 0.5}, "equip": "Barbell", "gentle": False},
    {"name": "DB RDL", "impact": {"Hamstrings/Glutes": 1.0}, "secondary": {"Upper Back": 0.5}, "equip": "Dumbbells", "gentle": False},
    {"name": "45-Degree Hyperext", "impact": {"Hamstrings/Glutes": 1.0}, "secondary": {"Upper Back": 0.5}, "equip": "Bench", "gentle": True},
    {"name": "Leg Extension", "impact": {"Quads": 1.0}, "secondary": {}, "equip": "Selectorized", "gentle": True},
    {"name": "Front Squat", "impact": {"Quads": 1.0}, "secondary": {"Hamstrings/Glutes": 0.5, "Upper Back": 0.5}, "equip": "Barbell", "gentle": False},
    {"name": "Weighted Step-Ups", "impact": {"Quads": 1.0}, "secondary": {"Hamstrings/Glutes": 1.0}, "equip": "Dumbbells", "gentle": False},
    {"name": "Weighted Walking Lunges", "impact": {"Quads": 1.0}, "secondary": {"Hamstrings/Glutes": 1.0}, "equip": "Dumbbells", "gentle": False},
    {"name": "Sissy Squat (Machine)", "impact": {"Quads": 1.0}, "secondary": {}, "equip": "Selectorized", "gentle": True},
    {"name": "Belt Squat", "impact": {"Quads": 1.0}, "secondary": {"Hamstrings/Glutes": 0.5}, "equip": "Plate-Loaded", "gentle": True},
    {"name": "Good Mornings", "impact": {"Hamstrings/Glutes": 1.0}, "secondary": {"Upper Back": 0.5}, "equip": "Barbell", "gentle": False},
    {"name": "Glute Ham Raise", "impact": {"Hamstrings/Glutes": 1.0}, "secondary": {"Calves": 0.5}, "equip": "Bench", "gentle": False},
    {"name": "Hip Thrust (Barbell)", "impact": {"Hamstrings/Glutes": 1.0}, "secondary": {"Quads": 0.5}, "equip": "Barbell", "gentle": False},
    {"name": "Machine Hip Thrust", "impact": {"Hamstrings/Glutes": 1.0}, "secondary": {"Quads": 0.5}, "equip": "Plate-Loaded", "gentle": True},
    {"name": "Single Leg Press", "impact": {"Quads": 1.0}, "secondary": {"Hamstrings/Glutes": 0.5}, "equip": "Sled Machine", "gentle": True},
    {"name": "Box Squat", "impact": {"Quads": 1.0}, "secondary": {"Hamstrings/Glutes": 1.0}, "equip": "Barbell", "gentle": False},

    # --- BODYWEIGHT DENSITY (1min Discovery / 5min Training) ---
    {"name": "Dips (Bodyweight)", "impact": {"Pectorals": 1.0}, "secondary": {"Triceps": 0.5, "Front Delts": 0.5}, "equip": "Bodyweight", "gentle": False},
    {"name": "Pull-Ups (Wide Grip)", "impact": {"Upper Back": 1.0}, "secondary": {"Rear Delts": 0.5, "Biceps": 0.5}, "equip": "Bodyweight", "gentle": False},
    {"name": "Chin-Ups (Bodyweight)", "impact": {"Upper Back": 1.0}, "secondary": {"Biceps": 1.0}, "equip": "Bodyweight", "gentle": False},
    {"name": "Neutral Grip Pull-Ups", "impact": {"Upper Back": 1.0}, "secondary": {"Biceps": 0.5, "Rear Delts": 0.5}, "equip": "Bodyweight", "gentle": False},
    {"name": "Push-Ups (Standard)", "impact": {"Pectorals": 1.0}, "secondary": {"Triceps": 0.5, "Front Delts": 0.5}, "equip": "Bodyweight", "gentle": True},
    {"name": "Diamond Push-Ups", "impact": {"Triceps": 1.0}, "secondary": {"Pectorals": 0.5, "Front Delts": 0.5}, "equip": "Bodyweight", "gentle": True},
    {"name": "Air Squats", "impact": {"Quads": 1.0}, "secondary": {"Hamstrings/Glutes": 0.5}, "equip": "Bodyweight", "gentle": True},
    {"name": "Bodyweight Walking Lunges", "impact": {"Quads": 1.0}, "secondary": {"Hamstrings/Glutes": 1.0}, "equip": "Bodyweight", "gentle": True},
    {"name": "Step-Ups (Low Box)", "impact": {"Quads": 1.0}, "secondary": {"Hamstrings/Glutes": 0.5}, "equip": "Bodyweight", "gentle": True},
    {"name": "Step-Ups (High Box)", "impact": {"Hamstrings/Glutes": 1.0}, "secondary": {"Quads": 0.5}, "equip": "Bodyweight", "gentle": False},
    {"name": "Nordic Curls (Bodyweight)", "impact": {"Hamstrings/Glutes": 1.0}, "secondary": {}, "equip": "Bodyweight", "gentle": False},
    {"name": "Hanging Leg Raises", "impact": {"Abs": 1.0}, "secondary": {"Forearms": 0.5}, "equip": "Bodyweight", "gentle": False},
    {"name": "Ab Wheel Rollouts", "impact": {"Abs": 1.0}, "secondary": {"Upper Back": 0.5}, "equip": "Bodyweight", "gentle": False},

    # --- SPECIALISTS ---
    {"name": "Face Pulls", "impact": {"Rear Delts": 1.0}, "secondary": {"Side Delts": 0.5, "Upper Back": 0.5}, "equip": "Cables", "gentle": True},
    {"name": "Reverse Pec Deck", "impact": {"Rear Delts": 1.0}, "secondary": {"Side Delts": 0.5, "Upper Back": 0.5}, "equip": "Selectorized", "gentle": True},
    {"name": "Cable Lateral Raise", "impact": {"Side Delts": 1.0}, "secondary": {}, "equip": "Cables", "gentle": True},
    {"name": "DB Lateral Raise", "impact": {"Side Delts": 1.0}, "secondary": {}, "equip": "Dumbbells", "gentle": True},
    {"name": "Machine Lateral Raise", "impact": {"Side Delts": 1.0}, "secondary": {}, "equip": "Selectorized", "gentle": True},
    {"name": "Tricep Pushdown", "impact": {"Triceps": 1.0}, "secondary": {}, "equip": "Cables", "gentle": True},
    {"name": "Overhead Cable Ext", "impact": {"Triceps": 1.0}, "secondary": {}, "equip": "Cables", "gentle": True},
    {"name": "Skull Crushers (DB)", "impact": {"Triceps": 1.0}, "secondary": {}, "equip": "Dumbbells", "gentle": True},
    {"name": "Barbell Bicep Curl", "impact": {"Biceps": 1.0}, "secondary": {}, "equip": "Barbell", "gentle": True},
    {"name": "Hammer Curl (DB)", "impact": {"Biceps": 1.0}, "secondary": {}, "equip": "Dumbbells", "gentle": True},
    {"name": "Preacher Curl (Mach)", "impact": {"Biceps": 1.0}, "secondary": {}, "equip": "Selectorized", "gentle": True},
    {"name": "Standing Calf Raise", "impact": {"Calves": 1.0}, "secondary": {}, "equip": "Selectorized", "gentle": True},
    {"name": "Seated Calf Raise", "impact": {"Calves": 1.0}, "secondary": {}, "equip": "Plate-Loaded", "gentle": True},
    {"name": "Calf Press (on LP)", "impact": {"Calves": 1.0}, "secondary": {}, "equip": "Sled Machine", "gentle": True},
    {"name": "Straight Arm Pulldown", "impact": {"Upper Back": 1.0}, "secondary": {"Triceps": 0.5}, "equip": "Cables", "gentle": True},
    {"name": "Donkey Calf Raise", "impact": {"Calves": 1.0}, "secondary": {}, "equip": "Selectorized", "gentle": True},
    {"name": "Tibialis Raise", "impact": {"Calves": 0.5}, "secondary": {}, "equip": "Dumbbells", "gentle": True},
    {"name": "Spider Curl", "impact": {"Biceps": 1.0}, "secondary": {}, "equip": "Dumbbells", "gentle": True},
    {"name": "Concentration Curl", "impact": {"Biceps": 1.0}, "secondary": {}, "equip": "Dumbbells", "gentle": True},
    {"name": "Cable Bicep Curl", "impact": {"Biceps": 1.0}, "secondary": {}, "equip": "Cables", "gentle": True},
    {"name": "Incline DB Curl", "impact": {"Biceps": 1.0}, "secondary": {}, "equip": "Dumbbells", "gentle": True},
    {"name": "Reverse Fly (DB)", "impact": {"Rear Delts": 1.0}, "secondary": {"Upper Back": 0.5}, "equip": "Dumbbells", "gentle": True},
    {"name": "Wrist Curls (Barbell)", "impact": {"Forearms": 1.0}, "secondary": {}, "equip": "Barbell", "gentle": True},
    {"name": "Reverse Wrist Curls", "impact": {"Forearms": 1.0}, "secondary": {}, "equip": "Barbell", "gentle": True},
    {"name": "Cable Crunches", "impact": {"Abs": 1.0}, "secondary": {}, "equip": "Cables", "gentle": True},
    {"name": "Dumbbell Shrugs", "impact": {"Upper Back": 1.0}, "secondary": {"Forearms": 0.5}, "equip": "Dumbbells", "gentle": True},
    {"name": "Barbell Shrugs", "impact": {"Upper Back": 1.0}, "secondary": {"Forearms": 0.5}, "equip": "Barbell", "gentle": True},
    {"name": "Farmer's Walk", "impact": {"Forearms": 1.0, "Upper Back": 1.0}, "secondary": {"Quads": 0.5, "Hamstrings/Glutes": 0.5}, "equip": "Dumbbells", "gentle": False}
]